from step import Step

x = Step('*')
p = Step('p')
span = Step('span')
div = Step('div')
form = Step('form')
input = Step('input')
textarea = Step('textarea')
a = Step('a')
html = Step('html')
body = Step('body')
label = Step('label')
select = Step('select')
option = Step('option')
h1 = Step('h1')
ul = Step('ul')
li = Step('li')
img = Step('img')
table = Step('table')
thead = Step('thead')
tbody = Step('tbody')
tr = Step('tr')
td = Step('td')
any_field = Step('*[self::input or self::select or self::textarea]')
script = Step('script')
